# This will be used for errors in the console and as a fallback when a user's language isn't on the server.
default-locale: "en-US"
# Downloads updates from Spigot automatically
auto-updater-enabled: true
# The block that will act as a grave upon player death. For Nexo blocks, make it nexo-namespace:block_name (example: nexo-mycustomblocks:custom_block)
grave-block: "minecraft:stone_bricks"
# Whether to send the player's death coordinates to them in chat
send-coordinates: true