name: ExtraGraves
description: Vanilla Graves with support for CuriosPaper and more!
main: me.cocolennon.extragraves.Main
version: 1.0.5
author: Cocolennon
api-version: '1.21.11'
dependencies:
  server:
    Nexo:
      load: BEFORE
      required: true
      join-classpath: true
    CuriosPaper:
      load: BEFORE
      required: true
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: true
      join-classpath: true
    WorldGuardExtraFlagsPlus:
      load: BEFORE
      required: true
      join-classpath: true
permissions:
  extragraves.grave-on-death:
    description: Allows players to have their stuff kept in a grave when dying
    default: true
  extragraves.break-graves:
    description: Allows players to break graves